services:
  - type: web
    name: sms-cleaner-bot
    runtime: python
    region: oregon
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
